### PR TITLE
Fix support for latest toolchains / PlatformIO packages

### PR DESCRIPTION
**Pull request by quiret**
**Summary**

Fix building using latest STM32 toolchains for the Marlin firmware. The expected location of the PlatformIO build script has changed thus leading to a build failure. This PR fixes it.

Please see PR https://github.com/MarlinFirmware/Marlin/pull/25327 for further details. Hit me up once you have merged this PR so that we can remove the odd-ball dependency from Marlin FW!

**Closing issues**

https://github.com/MarlinFirmware/Marlin/pull/25327

### CODE REVIEW

**Comment by quiret** [comment]
Merging could break current Marlin compilation of stm_flashdrive enabled builds so please wait.

**Comment by rhapsodyv** [comment]
Hi,

Thanks for the contribution.

But merging this at my branch would not be the "best/right" way to update marlin framework.

When we are using GitHub links for framework selection in marlin platformio.ini file, every time we change any code of the branch, we need to create a new branch to generate a new link and update the platformio.ini references.

This is annoying, I know, but we found that is the unique reliable way to force pio to update code when using links to GitHub. Without updating the link, pio will not update the code that is already downloaded by users, only new fresh pio installs will see the new code.

That being said, you should send a PR to marlin changing the framework link direct for your branch. If it don't work with usb host code yet, you can just update the non usb host envs in the marlin pio file.

Hint: don't point the link to a working/dev branch, because the same reason above - point to a "name versioned" branch like I did.

This should be temporary, until stm32duino merge the usb host code...

**Comment by quiret** [comment]
Yes, you are right. There is a problem updating GitHub branches when the .zip archive system is used instead of the Git version tracking integration. Thanks for recommending the approach of taking my fork for it. Yes I will follow your guidance with the separate branches for each update.

**Comment by quiret** [comment]
@rhapsodyv Do you have a PR waiting to be merged for the USB host code? You mentioned that your fork is temporary aswell.

**Pull request closed without merging**
